### ISSUE TITLE
core.mjs:7635 ERROR Error: NG0203: inject() 

### ISSUE THREAD

**Issue by keirymb** [ankush1802/Angular14GoogleMaps#1]
I been trying the same exact example as shown in this repository. When I try to run and display the map the following error appears. 

core.mjs:7635 ERROR Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `EnvironmentInjector#runInContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:4775:15)
    at ɵɵinject (core.mjs:4786:12)
    at Module.ɵɵdirectiveInject (core.mjs:10868:16)
    at NodeInjectorFactory.GoogleMap_Factory [as factory] (google-maps.mjs:432:1)
    at getNodeInjectable (core.mjs:3523:44)
    at instantiateAllDirectives (core.mjs:12689:27)
    at createDirectivesInstances (core.mjs:12113:5)
    at ɵɵelementStart (core.mjs:15243:9)
    at GooglemapComponent_div_2_Template (googlemap.component.html:3:1)
    at executeTemplate (core.mjs:12084:9) 

Can someone help me?

**Comment by ankush1802** [comment]
@keirymb which angular version you are using and can you share some screen shot

**Comment by keirymb** [comment]
I am using version 14.2 

Do you want a screenshot of the error or the program itself?

**Comment by ankush1802** [comment]
It's better if you share both I will check and update you asap

**Comment by keirymb** [comment]
![error](https://user-images.githubusercontent.com/113727612/190922883-9501bf02-c4e2-42bc-944e-a69fb5f6bb20.PNG)

Please see below the code. 
If you prefer I can email you the whole project. 
**googlemap.component.html**
`<h2>Products</h2>

  <google-map height="400px"
              width="750px"
              [center]="center"
              [zoom]="zoom"
              (mapClick)="moveMap($event)"
              (mapMousemove)="move($event)">
  </google-map>
`
**googlemap.component.ts**
`import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-googlemap',
  templateUrl: './googlemap.component.html',
  styleUrls: ['./googlemap.component.css']
})
export class GooglemapComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  display : any;
  center: google.maps.LatLngLiteral = {lat: 24, lng: 12};
  zoom = 4;

  moveMap(event: google.maps.MapMouseEvent) {
    if(event.latLng!= null)
    this.center = (event.latLng.toJSON());
  }

  move(event: google.maps.MapMouseEvent) {
    if(event.latLng != null)
    this.display = event.latLng.toJSON();
  }
}
`
**app-routing.module.ts**
`import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { GooglemapComponent } from './googlemap/googlemap.component';

const routes: Routes = [
  {path:'',component:GooglemapComponent}];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }`

**app.component.html**
`<app-top-bar></app-top-bar>
<div class="container">
  <router-outlet></router-outlet>
</div>`

**app.module.ts**
`import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { ReactiveFormsModule } from '@angular/forms';
import { GoogleMapsModule } from '@angular/google-maps';
import { HttpClientModule, HttpClientJsonpModule } from '@angular/common/http';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { TopBarComponent } from './top-bar/top-bar.component';
import { GooglemapComponent } from './googlemap/googlemap.component'


@NgModule({
  declarations: [
    AppComponent,
    TopBarComponent,
    GooglemapComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    ReactiveFormsModule,
    GoogleMapsModule,
    HttpClientModule,
    HttpClientJsonpModule
  ],
  providers: [],
  bootstrap: [AppComponent],
  exports: [
    GooglemapComponent,
  ],
})

export class AppModule { }
`

**app.component.ts**
`import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'my-app';
}

`

**Comment by ankush1802** [comment]
Share your source code on ankush1802@outlook.com

**Comment by keirymb** [comment]
Please check your email. Thank you for your help

**Comment by ankush1802** [comment]
Will reply with solution asap

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
